{% set name = "age" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src
    url: https://github.com/FiloSottile/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 71f69e5699a0b94aa1ca55b9b86b5bcf014f0c1412608a7a60b3e5fbbc553a77

build:
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses
    - go build -v -o $PREFIX/bin/age ./cmd/age  # [not win]
    - go build -v -o $PREFIX/bin/age-keygen ./cmd/age-keygen  # [not win]
    - go build -v -o %LIBRARY_BIN%\age.exe .\cmd\age  # [win]
    - go build -v -o %LIBRARY_BIN%\age-keygen.exe .\cmd\age-keygen  # [win]
    # Clear out cache to avoid file not removable warnings
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)  # [unix]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - age --help
    - age-keygen --help

about:
  home: https://github.com/FiloSottile/age
  license: BSD-3-Clause
  license_file:
    - src/LICENSE
    - library_licenses/
  summary: age is a simple, modern and secure file encryption tool, format, and Go library.
  dev_url: https://github.com/FiloSottile/age

extra:
  recipe-maintainers:
    - pavelzw
