schema_version: 1

context:
  name: age
  version: "1.3.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/FiloSottile/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: b07c28c6c4bdafa272073a310b75bc22c49da8904585a89c30e5ca4233e63843
    target_directory: src

build:
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses
    - if: not win
      then:
        - go build -v -o $PREFIX/bin/age ./cmd/age
        - go build -v -o $PREFIX/bin/age-keygen ./cmd/age-keygen
      else:
        - go build -v -o %LIBRARY_BIN%\age.exe .\cmd\age
        - go build -v -o %LIBRARY_BIN%\age-keygen.exe .\cmd\age-keygen
    - if: unix
      then: chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - age --help
      - age-keygen --help

about:
  license: BSD-3-Clause
  license_file:
    - src/LICENSE
    - library_licenses/
  summary: age is a simple, modern and secure file encryption tool, format, and Go library.
  homepage: https://github.com/FiloSottile/age
  repository: https://github.com/FiloSottile/age

extra:
  recipe-maintainers:
    - pavelzw
